/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_commontest_jniDemo_JniDemoActivity */

#ifndef _Included_com_example_test_commontest_jniDemo_JniDemoActivity
#define _Included_com_example_test_commontest_jniDemo_JniDemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_commontest_jniDemo_JniDemoActivity
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_commontest_jniDemo_JniDemoActivity_getStringFromJni
  (JNIEnv *, jobject);


/**
 *
 */
JNIEXPORT jstring JNICALL
Java_com_example_test_commontest_jniDemo_JniDemoActivity_createFile(JNIEnv *env, jobject instance,
                                                                    jstring fileName_) ;


/**
 * tcp 通信
 */
JNIEXPORT void JNICALL
        Java_com_example_test_commontest_jniDemo_JniDemoActivity_nativeStartTcpServer(JNIEnv *env,
                                                                                      jobject instance,
                                                                                      jint port);


#ifdef __cplusplus
}
#endif
#endif
