/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <bits/stringfwd.h>
#include <string>
/* Header for class com_example_test_commontest_jniDemo_JniDemoActivity */

#ifndef _Included_com_example_test_commontest_jniDemo_JniDemoActivity
#define _Included_com_example_test_commontest_jniDemo_JniDemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_commontest_jniDemo_JniDemoActivity
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_commontest_jniDemo_JniDemoActivity_getStringFromJni
  (JNIEnv *, jobject);


/**
 *
 */
JNIEXPORT jstring JNICALL
Java_com_example_test_commontest_jniDemo_JniDemoActivity_createFile(JNIEnv *env, jobject instance,
                                                                    jstring fileName_) ;


/**
 * tcp 通信
 * Signature: ([Ljava/lang/String;)
 */
JNIEXPORT void JNICALL
        Java_com_example_test_commontest_jniDemo_JniDemoActivity_nativeStartTcpServer(JNIEnv *env,
                                                                                      jobject instance,
                                                                                      jstring host,
                                                                                      jstring path,
                                                                                      jint port,
                                                                                      jstring strMsg,
                                                                                      jobjectArray message);


JNIEXPORT void JNICALL
        Java_com_example_test_commontest_jniDemo_JniDemoActivity_CallByJni(JNIEnv *env,
                                                                           jobject obj,
                                                                           char * buffer, int length);


void setRequest(JNIEnv * env, jobject obj, jobjectArray messageObj, std::string message);

int HttpGet(const char *server,const char *url);
int GetHttpResponseHead(int sock,char *buf,int size);
#ifdef __cplusplus
}
#endif
#endif
